### ISSUE TITLE
molecules/HeaderDropDownOtherの区分・命名の最適化

### ISSUE THREAD

**Issue by fukudomeh** [fukudomeh/t-met_front#23]

**Comment by fukudomeh** [comment]
# 作業内容
## molecules/HeaderDropDownOtherをorganisms/Headerに配置する
### 概要
HeaderDropDownOtherコンポーネントについて、現在はmolecules以下に配置をしているが、コンポーネントファイルのみを切り出し、organisms/Header/に配置する。

### 意図
HeaderDropDownOtherコンポーネントはコンテキストに依存した仕様のコンポーネントであり、しかorganismsと分類するほど役割を持つものではない。
AppHeaderコンポーネント内でのみ使用されるため、AppHeaderコンポーネントの一部とすることで保守性の向上を図る。

### イメージ
#### 作業前
```
components/
  ├ molecules/
  │  ├ HeaderDropDownOther/
  │    ├  index.tsx
  │    ├  HeaderDropDownOther.tsx
  │    ├  stories.tsx
  │    └  types.tsx
  │                 
  ├ organisms/
    ├ AppHeader/
      ├  index.tsx
      ├  AppHeader.tsx
      ├  stories.tsx
      └  types.tsx                   
```

#### 作業後
```
components/
  ├ molecules/
  │  ├ 
  │
  ├ organisms/
    ├ AppHeader/
      ├  index.tsx
      ├  AppHeader.tsx
      ├  stories.tsx
      ├  types.tsx 
      └  HeaderDropDownOther.tsx                  
```

**Comment by fukudomeh** [comment]
HeaderDropDownOtherコンポーネントの移植後、
AppHeaderコンポーネントからHeaderDropDownOtherコンポーネントをimportする箇所を修正する際は競合が起こらないように、必ず一度mainブランチの更新を確認して行ってください。

**Comment by r-kunisawa** [comment]
すみません, 作業開始時のコメントを入れ忘れていました。以後気を付けます。
