### ISSUE TITLE
molecules/SignInIdInputAreaの区分・命名の最適化

### ISSUE THREAD

**Issue by fukudomeh** [fukudomeh/t-met_front#26]

**Comment by fukudomeh** [comment]
# 作業内容
## molecules/SignInIdInputAreaをorganisms/SignInに配置する
### 概要
SignInIdInputAreaコンポーネントについて、現在はmolecules以下に配置をしているが、コンポーネントファイルのみを切り出し、organisms/SignIn/に配置する。

### 意図
SignInIdInputAreaコンポーネントはSignInコンポーネント以外で使用されないため、コンポーネントの一部とすることで保守性の向上を図る。

### イメージ
#### 作業前
```
components/
  ├ molecules/
  │  ├ SignInIdInputArea/
  │    ├  index.tsx
  │    ├  SignInIdInputArea.tsx
  │    ├  stories.tsx
  │    └  types.tsx
  │                 
  ├ organisms/
    ├ SignIn/
      ├  index.tsx
      ├  SignIn.tsx
      ├  stories.tsx
      └  types.tsx                   
```

#### 作業後
```
components/
  ├ molecules/
  │  ├ 
  │
  ├ organisms/
    ├ SignIn/
      ├  index.tsx
      ├  SignIn.tsx
      ├  stories.tsx
      ├  types.tsx 
      └  SignInIdInputArea.tsx                  
```

**Comment by fukudomeh** [comment]
SignInIdInputAreaコンポーネントの移植後、
SignInコンポーネントからSignInIdInputAreaコンポーネントをimportする箇所を修正する際は競合が起こらないように、必ず一度mainブランチの更新を確認して行ってください。

**Comment by r-kunisawa** [comment]
こちらの作業行います
