### ISSUE TITLE
molecules/SearchConditionsButtonの区分・命名の最適化

### ISSUE THREAD

**Issue by fukudomeh** [fukudomeh/t-met_front#33]

**Comment by fukudomeh** [comment]
# 作業内容
## molecules/SearchConditionsButton→SettingButtons命名変更
### 概要
SearchConditionsButtonコンポーネントについて、現在はコンテキストに依存する名前となっているため、命名をSettingButtons等に変更する。

### 意図
コンポーネント名から内容を読み取れること
コンポーネントがmolecules相当の汎用性であること

### 変更点
types.ts内、「isSearchWord」プロパティを、「clearDisabled」等に変更する
  → component内のprops.isSearchWordをprops.clearDisabledへと変更

### 影響範囲
molecules/SearchConditionsButtonコンポーネントは、現在organisms/SearchAreaコンポーネントからのみimportされているため、organisms/SearchAreaコンポーネントでのimport文を変更する
⇑
isSearchWordプロパティがclearDisabledプロパティと名前が変わっているため、organisms/SearchAreaコンポーネントに対して適用を行う。

**Comment by r-kunisawa** [comment]
こちら着手します。
