### ISSUE TITLE
storybook上でpublicフォルダ下の静的画像が表示されない

### ISSUE THREAD

**Issue by r-kunisawa** [fukudomeh/t-met_front#41]
## 概要
storybookでpublicディレクトリ以下に配置した画像が表示されていない。

## 症状が確認されたコンポーネントとその要素
Template/MasterDataList/UserMaster等のHeaderコンポーネントを使用しているコンポーネントのlogoの部分

## 推測される原因
Next.jsだとimgタグ内でのpublicディレクトリへの参照パスに"/(public下のディレクトリのパス)"のように記述しても参照できないためと推測

## 対処方法
package.jsonの10行目あたりの

```
"storybook": "start-storybook -p 6006"
```

を下記のように書き換えた状態でstorybookを再起動する

```
"storybook": "start-storybook -s ./public -p 6006",
```

## 備考
[対象方法の参考にした記事](https://xenox.dev/next-image-with-storybookjs/)

package.jsonを書き換えるやり方が正しいのか判断ができないためご指示等いただければ幸いです。

## 追記
上記の対応についてですが, storybook起動のコマンドを下記のように指定することでも同様の結果が得られるため, こちらのissueが不要でしたらcloseいただければと思います。

```
yarn storybook
↓
yarn storybook -s ./public
```

**Comment by fukudomeh** [comment]
issueありがとうございます！
npm script内にpublicベースを指定すれば正しい動作が見込めると思いますので、npm script内のstorybookコマンドの書き換えによって対応を行いたいと考えます。
よければ、対応していただければ幸いに存じ上げます！m(_ _)m
（お時間の都合上難しい等の問題があれば、コメントしていただければIWS内で担当を振ります！）

**Comment by r-kunisawa** [comment]
> npm script内にpublicベースを指定すれば正しい動作が見込めると思いますので、npm script内のstorybookコマンドの書き換えによって対応を行いたいと考えます。
> よければ、対応していただければ幸いに存じ上げます！m(_ _)m

承知いたしました, こちら対応させていただきます。
