### ISSUE TITLE
organisms/SearchArea内、molesules/AlertDialogが正しく動作していない

### ISSUE THREAD

**Issue by fukudomeh** [fukudomeh/t-met_front#50]
```tsx
      <AlertDialog
        open={alertOpen}
        setOpen={setAlertOpen}
        message={alertState}
        onOkClick={() => ""}
      />
```

- okClick時に呼び出される関数が空文字になっている
    => alertStateに従って呼び出される処理を分岐する
- messageにalertStateが渡されてしまっている
    => 旧ver（SearchAlert）内の警告文を参考に、messageは文字列（或いは、alertStateに対し適当な文字列を呼び出す関数）を渡す

**Comment by r-kunisawa** [comment]
こちら着手します。
